#!/usr/bin/env bash

uv run src/analysis/prepare_exp_c_faithfulness_sheet.py \
  --queries leaderboard_queries.json \
  --chunks data/processed/chunks.jsonl \
  --closed_answers data/answers/leaderboard_answers_v1_closed_book.json \
  --rag_answers data/answers/leaderboard_answers_v4.json \
  --out_csv analysis/exp_c/faithfulness_sheet.csv \
  --sample_size 50 \
  --seed 13 \
  --bm25_dir indexes/bm25_v3 \
  --dense_dir indexes/dense_gte-Qwen2-7B-instruct_v2 \
  --embed_model Alibaba-NLP/gte-Qwen2-7B-instruct \
  --embed_quant_backend 8bit \
  --device cuda:0 \
  --w_dense 0.5 \
  --w_sparse 0.5 \
  --k_dense 200 \
  --k_sparse 200 \
  --rrf_k 60 \
  --sparse_title_weight 3 \
  --sparse_heading_weight 2 \
  --sparse_body_weight 1 \
  --sparse_add_bigrams \
  --sparse_prf \
  --sparse_prf_k 8 \
  --sparse_prf_terms 6 \
  --sparse_prf_alpha 0.65 \
  --k_retrieve 100 \
  --stage1_k 60 \
  --mmr_lambda 0.75 \
  --temporal_boost_weight 0.12 \
  --top_ctx 3
